### ISSUE TITLE
[about] Broken link to SMASH HIFI

### ISSUE THREAD

**Issue by KevinGimbel** [kahlil/kahlillechelt.com#1]
Hey!

The link to SMASH HIFI on https://www.kahlillechelt.com/about/ is broken. <3

Great seeing you switch to Hugo, feel free to ask me if you need any help settings things up or have any questions. :+1:

**Comment by khalillechelt** [comment]
Dankeschön!

**Comment by khalillechelt** [comment]
Fixed! Thanks again!

**Comment by KevinGimbel** [comment]
You're welcome!
